obras-1213-web/obras-1213/Controllers/ObrasController.cs
using obras_1213.Models;
using obras_1213.Models.View;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace obras_1213.Controllers
{
    public class ObrasController : BaseController
    {
        //
        // GET: /Obras/
        [HttpGet, Authorize]
        public ActionResult Index()
        {
            return View(new AllWorksViewModel());
        }

        [HttpPost, Authorize]
        public ActionResult Index(AllWorksViewModel cfg)
        {
            return View(cfg);
        }

        [HttpGet, Authorize]
        public ActionResult Details(int id)
        {
            try
            {
                return View("Details", new WorkViewModel(Work.Find(id)));
            }
            catch (ModelException ex)
            {
                ModelState.AddModelError("", ex);
                return Index();
            }
        }

        [HttpGet, Authorize]
        public ActionResult Download(int id)
        {
            try
            {
                Response.ContentType = "text/xml; charset=utf-16";
                Response.AddHeader("Content-Disposition", "attachment; filename=\"obra" + id.ToString() + ".xml\"");
                return this.Content(new WorkViewModel( Work.Find(id)).SerializeToString(),
                    "text/xml", System.Text.Encoding.Unicode);
            }
            catch (ModelException ex)
            {
                ModelState.AddModelError("", ex);
                return Index();
            }
        }

        [HttpPost]
        public ActionResult OfflineDetails( )
        {
            try
            {
                return View("DetailsOffline", WorkViewModel.Deserialize(Request.Files["WorkFile"].InputStream));
            }
            catch (ModelException ex)
            {
                ModelState.AddModelError("", ex);
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpGet, Authorize(Roles = "receptionist")]
        public ActionResult New()
        {
            return View(new NewWorkViewModel() { ShopID = this.ShopID });
        }

        [HttpPost, Authorize(Roles = "receptionist")]
        public ActionResult New(NewWorkViewModel newWork)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    return RedirectToAction("Details", new { id = Work.Insert(newWork.ShopID, newWork.CarLicensePlate, newWork.Actions) });
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(newWork);
        }

        [Authorize(Roles = "receptionist")]
        public ActionResult ChangeState(int id, string state)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Work.Find(id).State = state;
                    return RedirectToAction("Details", new { id = id });
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [HttpPost, Authorize(Roles = "receptionist")]
        public ActionResult AddAction(int id, int actionId, int employeeId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Work.Find(id).AddAction(actionId, employeeId))
                    {
                        return RedirectToAction("Details", new { id = id });
                    }
                    ModelState.AddModelError("", "Não foi possível adicionar o acto à obra.");
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [Authorize(Roles = "receptionist")]
        public ActionResult RemoveAction(int id, int actionId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Work.Find(id).Actions.First(a => a.ID == actionId).Remove())
                    {
                        return RedirectToAction("Details", new { id = id });
                    }
                    ModelState.AddModelError("", "Não foi possível adicionar o acto à obra.");
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [Authorize]
        public ActionResult CompleteAction(int id, int actionId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    WorkAction wa = Work.Find(id).Actions.First(a => a.ID == actionId);
                    if (wa.CurrentUserCanComplete)
                    {
                        wa.Complete();
                        return RedirectToAction("Details", new { id = id });
                    }
                    else
                    {
                        ModelState.AddModelError("", "Não tem autorização para completar este acto.");
                    }
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [HttpPost, Authorize]
        public ActionResult ChangeActionTime(int id, int actionId, string time)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    float actualTime;
                    if (time != null && float.TryParse(time, out actualTime))
                    {
                        WorkAction action = Work.Find(id).Actions.First(a => a.ID == actionId);
                        action.TimeWorked = actualTime;
                        action.CommitTime();
                        return RedirectToAction("Details", new { id = id });
                    }
                    ModelState.AddModelError("", "O número de horas não está num formato correcto.");
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [HttpPost, Authorize(Roles = "receptionist")]
        public ActionResult RemovePart(int id, string partId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Work.Find(id).Parts.First(p => p.ID.Equals(partId)).Remove())
                    {
                        return RedirectToAction("Details", new { id = id });
                    }
                    ModelState.AddModelError("", "Não foi possível remover essa peça da obra.");
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [HttpPost, Authorize(Roles = "receptionist")]
        public ActionResult AddPart(int id, WorkPart newPart)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Work.Find(id).AddPart(newPart))
                    {
                        return RedirectToAction("Details", new { id = id });
                    }
                    ModelState.AddModelError("", "Não é possível adicionar essa peça à obra. Será que já existe?");
                }
                catch (ModelException)
                {
                    ModelState.AddModelError("", "Não é possível adicionar essa peça à obra. Será que já existe?");
                }
            }
            return Details(id);
        }

        [HttpPost, Authorize(Roles = "receptionist")]
        public ActionResult InvoiceTo(int id, int customerId)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Work.Find(id).Facturar(customerId))
                    {
                        return RedirectToAction("Details", new { id = id });
                    }
                    ModelState.AddModelError("", "Não é possível facturar esta obra?");
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }

        [Authorize(Roles = "receptionist")]
        public ActionResult Pay(int id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Invoice inv = Work.Find(id).Invoice;
                    if (inv != null)
                    {
                        inv.Paid = true;
                        if (inv.Paid)
                        {
                            return RedirectToAction("Details", new { id = id });
                        }
                    }
                    ModelState.AddModelError("", "Não é possível pagar esta obra?");
                }
                catch (ModelException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return Details(id);
        }
    }
}

obras-1213-web/obras-1213/Views/Obras/Details.cshtml
@using obras_1213.Models
@using obras_1213.Models.View
@model WorkViewModel

@{
    ViewBag.Title = "Detalhes de obra";
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool isReceptionist = User.IsInRole("receptionist");
}

<h2>Detalhes de obra</h2>

@Html.ValidationSummary(false, "Não foi possível alterar a obra.")

<div class="container">
    <div class="row">
        <div class="span4">
            <dl class="dl-horizontal">
                <dt>Viatura</dt><dd>@Model.Work.CarLicense</dd>
                <dt>Duração estimada</dt><dd>@Model.Work.PredictedTime horas</dd>
                <dt>Valor previsto</dt><dd>@Model.Work.PredictedValue &euro;</dd>
            </dl>                
        </div>
        <div class="span8 text-right">
            <div class="btn-toolbar">
                <div class="btn-group">
                    <a class="btn @(Model.Work.Closed ? "btn-inverse" : (Model.Work.State.Equals("marcada") ? "btn-primary" : ""))" 
                        href="@(Model.Work.Closed || !isReceptionist ? "#" : Url.Action("ChangeState", new { id = Model.Work.ID, state = "marcada" }))">
                        Marcada</a>
                    <a class="btn @(Model.Work.Closed ? "btn-inverse" : (Model.Work.State.Equals("espera peças") ? "btn-primary" : ""))" 
                        href="@(Model.Work.Closed ? "#" : Url.Action("ChangeState", new { id = Model.Work.ID, state = "espera peças" }))">
                        Espera peças</a>
                    <a class="btn @(Model.Work.Closed ? "btn-inverse" : (Model.Work.State.Equals("em realização") ? "btn-primary" : ""))" 
                        href="@(Model.Work.Closed ? "#" : Url.Action("ChangeState", new { id = Model.Work.ID, state = "em realização" }))">
                        Em realização</a>
                    <a class="btn @(Model.Work.Invoiced || Model.Work.Paid ? "btn-inverse" : (Model.Work.State.Equals("concluída") ? "btn-primary" : ""))" 
                        href="@(Model.Work.Invoiced || !isReceptionist ? "#" : Url.Action("ChangeState", new { id = Model.Work.ID, state = "concluída" }))">
                        Concluída</a>
                    <a class="btn @(Model.Work.Invoiced ? "btn-primary" : "btn-inverse")" 
                        href="#">
                        Facturada</a>
                    <a class="btn @(Model.Work.Paid ? "btn-primary" : "btn-inverse")" 
                        href="#">
                        Paga</a>
                </div>
            </div>
            @if (Model.Work.Closed && !Model.Work.Invoiced && !Model.Work.Paid && isReceptionist)
            {
                <br />
                <form action="@Url.Action("InvoiceTo", new { id = Model.Work.ID })" method="post" class="form-inline">
                    @Html.Label("customerId", "Facturar ao cliente") @Html.DropDownList("customerId", Model.CustomersToSelect)
                    <button class="btn btn-success" type="submit">Emitir factura</button>
                </form>
            }
        </div>
    </div>
    <div class="row">
        <div class="span7">
            <h4>Actos</h4>
            <table class="table">
                <tr><th>Descrição</th><th>Funcionário</th><th>Horas</th><th></th></tr>
                @foreach (WorkAction a in Model.Work.Actions)
                {
                    <tr>
                        <td>@a.Description</td>
                        <td>@a.Employee.Name</td>
                        <td>
                            @if (a.Completed)
                            {
                                @a.TimeWorked
                            }
                            else
                            {
                                <form action="@Url.Action("ChangeActionTime", "Obras", new  { id = Model.Work.ID, actionId = a.ID })" method="post" class="inline-form nopadding nomargin">
                                    <div class="input-append">
                                        <input type="text" name="time" value="@a.TimeWorked" style="width:2em"/>
                                        <button class="btn btn-success" type="submit"><i class="icon-refresh"></i></button>
                                    </div>
                                </form>
                            }
                        </td>
                        <td style="text-align:center">
                            @if (a.Completed)
                            {
                                <i class="icon-ok"></i>
                            }
                            else if (a.CurrentUserCanComplete)
                            {
                                <a href="@Url.Action("CompleteAction", "Obras", new { id = Model.Work.ID, actionId = a.ID })" class="btn btn-warning">
                                    <i class="icon-ok"></i>
                                </a>
                            }
                            @if (!Model.Work.Closed && !a.Completed && isReceptionist)
                            {
                                <a href="@Url.Action("RemoveAction", "Obras", new { id = Model.Work.ID, actionId = a.ID })" class="btn btn-danger">
                                    <i class="icon-remove"></i>
                                </a>
                            }
                        </td>
                    </tr>
                }
                @if (!Model.Work.Closed && isReceptionist)
                {
                    <tr>
                        <form action="@Url.Action("AddAction", "Obras", new  { id = Model.Work.ID })" method="post" class="inline-form">
                            <td>@Html.DropDownList("actionId", Model.ActionsToSelect)</td>
                            <td>@Html.DropDownList("employeeId", Model.EmployeeToSelect)</td>
                            <td colspan="2"><button class="btn btn-success"><i class="icon-plus-sign"></i> Adicionar</button></td>
                        </form>
                    </tr>
                }
            </table>
        </div>
        <div class="span5">
            <h4>Peças</h4>
            <table class="table">
            <tr><th>Descrição</th><th>Quantidade</th><th>Preço</th><th></th></tr>
            @foreach (WorkPart p in Model.Work.Parts)
            {
                <tr><td>@p.Description</td><td>@p.Quantity</td><td>@(p.Price * p.Quantity) &euro;</td>
                    <td>
                        @if (!Model.Work.Closed)
                        {
                            <form action="@Url.Action("RemovePart", "Obras", new { id = Model.Work.ID })" 
                                class="inline-form nopadding nomargin" method="post">
                                <input type="hidden" name="partId" value="@p.ID" />
                                <button class="btn btn-danger"><i class="icon-remove"></i></button>
                            </form>
                        }
                    </td>
                </tr>
            }
            @if (!Model.Work.Closed)
            {
                <tr>
                <form action="@Url.Action("AddPart", "Obras", new { id = Model.Work.ID })" class="inline-form" method="post">
                    <td>@Html.DropDownList("newPart.ID", Model.PartsToSelect)</td>
                    <td><input name="newPart.Quantity" type="number" min="1" max="99" style="width:3em;"/></td>
                    <td colspan="2"><button class="btn btn-success btn" type="submit"><i class="icon-plus-sign"></i> Adicionar</button></td>
                </form>
                </tr>
            }
            </table>
        </div>
    </div>
    @if (Model.Work.Invoice != null)
    {
        <div class="row">
            <div class="span12">
                <h4>Factura</h4>
            </div>
            <div class="span6">
                <dl class="dl-horizontal">
                    <dt>Número</dt><dd>@Model.Work.Invoice.ID</dd>
                    <dt>Data</dt><dd>@Model.Work.Invoice.Date.ToShortDateString()</dd>
                    <dt>Estado</dt><dd class="@(Model.Work.Invoice.Paid ? "text-success" : "text-warning")">@Model.Work.Invoice.State</dd>
                    <dt>&nbsp;</dt><dd>&nbsp;</dd>
                    <dt>Cliente</dt><dd>@Model.Work.Invoice.Customer.Nome</dd>
                    <dt>&nbsp;</dt><dd>&nbsp;</dd>
                    <dt>Desconto</dt><dd>@Model.Work.Invoice.Discount %</dd>
                    <dt>Total</dt><dd>@Model.Work.Invoice.Total &euro;</dd>
                    @if (!Model.Work.Invoice.Paid && isReceptionist)
                    {
                        <dt>&nbsp;</dt><dd>&nbsp;</dd>
                        <dt>&nbsp;</dt><dd><a href="@Url.Action("Pay", new { id = Model.Work.ID })" class="btn btn-warning">Pagar</a></dd>
                    }
                </dl>
            </div>
            <div class="span6">
                <table class="table">
                    <tr><th></th><th>Descrição</th><th>Preço unitário</th><th>Quantidade</th><th>Valor</th></tr>
                    @{ 
                        decimal total = 0;
                        foreach (InvoiceLine l in Model.Work.Invoice.Lines)
                        {
                            <tr>
                                <td>@l.ID</td>
                                <td>@l.Description</td>
                                <td>@l.UnitPrice &euro;</td>
                                <td>@l.Quantity</td>
                                <td>@l.LineTotal &euro;</td>
                            </tr>
                            total += l.LineTotal;
                        }
                        <tr>
                            <td colspan="4" style="text-align: right !important"><i>Sub-total</i></td>
                            <td><i>@total &euro;</i></td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    }
</div>

obras-1213-web/obras-1213/Views/Obras/DetailsOffline.cshtml
@using obras_1213.Models
@using obras_1213.Models.View
@model WorkViewModel

@{
    ViewBag.Title = "Detalhes de obra";
    Layout = null;
}

<!DOCTYPE html>
<html>
    @Html.Partial("_Header")
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Obras 11/12</a>
        </div>
      </div>
    </div>

    <div class="container">

<h2>Detalhes de obra</h2>

@Html.ValidationSummary(false, "Não foi possível ler a obra.")

<div class="container">
    <div class="row">
        <div class="span4">
            <i>Modo desligado: imagem obtida a @Model.SaveDate</i>
            <dl class="dl-horizontal">
                <dt>Viatura</dt><dd>@Model.Work.CarLicense</dd>
                <dt>Duração estimada</dt><dd>@Model.Work.PredictedTime horas</dd>
                <dt>Valor previsto</dt><dd>@Model.Work.PredictedValue &euro;</dd>
            </dl>                
        </div>
        <div class="span8 text-right">
            <div class="btn-toolbar">
                <div class="btn-group">
                    <a class="btn disabled @(Model.Work.Closed ? "btn-inverse" : (Model.Work.State.Equals("marcada") ? "btn-primary" : ""))" 
                        href="/" onclick="return false;">
                        Marcada</a>
                    <a class="btn disabled @(Model.Work.Closed ? "btn-inverse" : (Model.Work.State.Equals("espera peças") ? "btn-primary" : ""))" 
                        href="/" onclick="return false;">
                        Espera peças</a>
                    <a class="btn disabled @(Model.Work.Closed ? "btn-inverse" : (Model.Work.State.Equals("em realização") ? "btn-primary" : ""))" 
                        href="/" onclick="return false;">
                        Em realização</a>
                    <a class="btn disabled @(Model.Work.Invoiced || Model.Work.Paid ? "btn-inverse" : (Model.Work.State.Equals("concluída") ? "btn-primary" : ""))" 
                        href="/" onclick="return false;">
                        Concluída</a>
                    <a class="btn disabled @(Model.Work.Invoiced ? "btn-primary" : "btn-inverse")" 
                        href="/" onclick="return false;">
                        Facturada</a>
                    <a class="btn disabled @(Model.Work.Paid ? "btn-primary" : "btn-inverse")" 
                        href="/" onclick="return false;">
                        Paga</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span7">
            <h4>Actos</h4>
            <table class="table">
                <tr><th>Descrição</th><th>Funcionário</th><th>Horas</th><th></th></tr>
                @foreach (WorkAction a in Model.Work.SerializedActions)
                {
                    <tr>
                        <td>@a.Description</td>
                        <td>@a.Employee.Name</td>
                        <td>@a.TimeWorked</td>
                        <td style="text-align:center">
                            @if (a.Completed)
                            {
                                <i class="icon-ok"></i>
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="span5">
            <h4>Peças</h4>
            <table class="table">
            <tr><th>Descrição</th><th>Quantidade</th><th>Preço</th><th></th></tr>
            @foreach (WorkPart p in Model.Work.SerializedParts)
            {
                <tr><td>@p.Description</td><td>@p.Quantity</td><td>@(p.Price * p.Quantity) &euro;</td>
                    <td>
                    </td>
                </tr>
            }
            </table>
        </div>
    </div>
    @if (Model.Work.WorkInvoice != null)
    {
        <div class="row">
            <div class="span12">
                <h4>Factura</h4>
            </div>
            <div class="span6">
                <dl class="dl-horizontal">
                    <dt>Número</dt><dd>@Model.Work.WorkInvoice.ID</dd>
                    <dt>Data</dt><dd>@Model.Work.WorkInvoice.Date.ToShortDateString()</dd>
                    <dt>Estado</dt><dd class="@(Model.Work.WorkInvoice.Paid ? "text-success" : "text-warning")">@Model.Work.WorkInvoice.State</dd>
                    <dt>&nbsp;</dt><dd>&nbsp;</dd>
                    <dt>Cliente</dt><dd>@Model.Work.WorkInvoice.Customer.Nome</dd>
                    <dt>&nbsp;</dt><dd>&nbsp;</dd>
                    <dt>Desconto</dt><dd>@Model.Work.WorkInvoice.Discount %</dd>
                    <dt>Total</dt><dd>@Model.Work.WorkInvoice.Total &euro;</dd>
                </dl>
            </div>
            <div class="span6">
                <table class="table">
                    <tr><th></th><th>Descrição</th><th>Preço unitário</th><th>Quantidade</th><th>Valor</th></tr>
                    @{ 
                        decimal total = 0;
                        foreach (InvoiceLine l in Model.Work.WorkInvoice.Lines)
                        {
                            <tr>
                                <td>@l.ID</td>
                                <td>@l.Description</td>
                                <td>@l.UnitPrice &euro;</td>
                                <td>@l.Quantity</td>
                                <td>@l.LineTotal &euro;</td>
                            </tr>
                            total += l.LineTotal;
                        }
                        <tr>
                            <td colspan="4" style="text-align: right !important"><i>Sub-total</i></td>
                            <td><i>@total &euro;</i></td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    }
</div>

               
    </div>
</body>
</html>

obras-1213-web/obras-1213/Views/Obras/Index.cshtml
@using obras_1213.Models
@using obras_1213.Models.View
@model AllWorksViewModel

@{
    ViewBag.Title = "Obras";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = 0;
}

<div class="container">
    <div class="row">
        <div class="span12">
            @Html.ValidationSummary(false)
        </div>
    </div>

    <div class="row">
        <div class="span4">
            <h2 class="nomargin">Obras em curso</h2>
        </div>
        <div class="span5 text-right">
            @if (User.IsInRole("receptionist")) 
            {
                <a href="@Url.Action("New")" class="btn btn-success">
                    <i class="icon-plus-sign"></i> Inserir uma obra nova
                </a>
            }
        </div>
        <div class="span3 text-right">
            <form action="@Url.Action("Index")" class="form-inline nomargin nopadding" method="post">
                @Html.HiddenFor(m => m.ClosedSince)
                <div class="input-prepend input-append">
                    <span class="add-on">Desde</span>
                    <input class="span2 date" name="OpenSince" type="text" value="@Model.OpenSince.ToShortDateString()" />
                    <button class="btn" type="submit"><i class="icon-refresh"></i></button>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <table class="table">
            <tr><th></th><th>Data de inserção</th><th>Estado</th><th>Valor estimado</th><th>Duração estimada</th><th>Viatura</th></tr>
            @{
                count = 0;
                foreach(Work w in Model.OpenWorks) {
                    ++count;
                    <tr><td><a href="@Url.Action("Details", "Obras", new { id = w.ID })">@w.ID <i class="icon-circle-arrow-right"></i></a></td>
                        <td>@w.IssuanceDate</td><td>@w.State</td><td>@w.PredictedValue €</td><td>@w.PredictedTime</td><td>@w.CarLicense</td></tr>
                }
                if (count == 0)
                {
                    <tr><td colspan="6"><i>Não existem obras abertas registadas no sistema desde @Model.OpenSince.ToShortDateString().</i></td></tr>
                }
            }
            </table>
        </div>
    </div>

    <div class="row">
        <div class="span4">
            <h2 class="nomargin nopadding">Obras concluídas</h2>
        </div>
        <div class="span8 text-right">
            <form action="@Url.Action("Index")" class="form-inline nomargin nopadding" method="post">
                @Html.HiddenFor(m => m.OpenSince)
                <div class="input-prepend input-append">
                    <span class="add-on">Desde</span>
                    <input class="span2 date" name="ClosedSince" type="text" value="@Model.ClosedSince.ToShortDateString()" />
                    <button class="btn" type="submit"><i class="icon-refresh"></i></button>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="span12">
            <table class="table">
            <tr><th></th><th>Data de inserção</th><th>Estado</th><th>Valor estimado</th><th>Duração estimada</th><th>Viatura</th></tr>
            @{
                count = 0;
                foreach(Work w in Model.ClosedWorks) {
                    ++count;
                    <tr><td><a href="@Url.Action("Details", "Obras", new { id = w.ID })">@w.ID <i class="icon-circle-arrow-right"></i></a></td>
                        <td>@w.IssuanceDate</td><td>@w.State</td><td>@w.PredictedValue €</td><td>@w.PredictedTime</td><td>@w.CarLicense</td></tr>
                }
                if (count == 0)
                {
                    <tr><td colspan="6"><i>Não existem obras concluídas registadas no sistema desde @Model.ClosedSince.ToShortDateString().</i></td></tr>
                }
            }
            </table>
        </div>
    </div>
</div>

obras-1213-web/obras-1213/Views/Obras/New.cshtml
@using obras_1213.Models.View
@model NewWorkViewModel
@{
    ViewBag.Title = "Nova Obra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nova Obra</h2>

@Html.ValidationSummary(true, "Não foi possível inserir a obra.")

@using (Html.BeginForm("New", "Obras", FormMethod.Post, new { Class = "form-horizontal" }))
{
    <div class="control-group">
        <label for="ShopID" class= "control-label">Oficina</label>
        <div class="controls">
            @Html.DropDownListFor(m => m.ShopID, Model.ShopsForSelect)
            @Html.ValidationMessageFor(m => m.ShopID)
        </div>
    </div>
    <div class="control-group">
        <label for="CarLicensePlate" class= "control-label">Viatura</label>
        <div class="controls">
            @Html.DropDownListFor(m => m.CarLicensePlate, Model.CarsForSelect)
            @Html.ValidationMessageFor(m => m.CarLicensePlate)
        </div>
    </div>
    <div class="control-group">
        <label for="Actions" class= "control-label">Actos a executar</label>
        <div class="controls">
            @Html.ListBoxFor(m => m.Actions, Model.ActionsForSelect)
            @Html.ValidationMessageFor(m => m.Actions)
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input type="submit" value="Criar" class="btn btn-success" />
        </div>
    </div>
}